eks_tunnel_local_port: 8443
kubeconfig_path: "{{ playbook_dir | dirname | dirname }}/.generated/kubeconfig"

backend_image: "{{ backend_repository_url }}:{{ initial_image_tag }}"
frontend_image: "{{ frontend_repository_url }}:{{ initial_image_tag }}"

backend_deployment: hospital-backend
backend_container: backend
frontend_deployment: hospital-frontend
frontend_container: frontend

ingress_name: hospital-ingress
alb_name: hospital-system-alb

load_balancer_controller_chart_version: "3.5.0"
metrics_server_chart_version: "3.14.0"
external_secrets_chart_version: "2.11.0"

cloudflare_record_name: "{{ app_domain_name }}"
cloudflare_record_type: CNAME
cloudflare_record_proxied: false
cloudflare_record_ttl: 1
cloudflare_alb_wait_retries: 30
cloudflare_alb_wait_delay: 20

demo_login_enabled: true

kubernetes_manifests:
  - namespace.yaml.j2
  - backend/configmap.yaml.j2
  - backend/service.yaml.j2
  - backend/hpa.yaml.j2
  - backend/pdb.yaml.j2
  - frontend/service.yaml.j2
  - frontend/hpa.yaml.j2
  - frontend/pdb.yaml.j2
  - rbac/github-actions-deploy.yaml.j2
  - policy/trusted-workloads.yaml.j2
  - policy/deploy-image-only.yaml.j2
  - policy/network.yaml.j2
  - ingress/ingress.yaml.j2

kubernetes_workload_manifests:
  - backend/deployment.yaml.j2
  - frontend/deployment.yaml.j2
