"""Run scripts/rotate-jwt-key.py against a temporary repository root.

The stack-up tests put fake ansible-playbook and kubectl first on PATH. The
fake playbook records its arguments and the key it received; the fake kubectl
answers with FAKE_SECRET_HASH and FAKE_DEPLOYMENT. Every run also checks that
the saved key appears in no output and on no command line.
"""

from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path
from unittest import TestCase, main
import json
import os
import re
import stat
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts/rotate-jwt-key.py"
SPEC = spec_from_file_location("rotate_jwt_key", SCRIPT)
rotate = module_from_spec(SPEC)
SPEC.loader.exec_module(rotate)

PLAYBOOK = "ansible/playbooks/backend-secret.yml"
OLD_KEY = "old-key-0123456789abcdef0123456789abcdef"
CONNECTION = "Host=db.example;Database=hospital;Username=app;Password=p a;ss"
ENV_LOCAL = f"""\
# Local values; see .env.example.

export CLOUDFLARE_ZONE_ID=zone123
export CLOUDFLARE_API_TOKEN=token-abc

export HOSPITALSYSTEM_CONNECTION_STRING='{CONNECTION}'
export HOSPITALSYSTEM_JWT_SECRET={OLD_KEY}

# Receives the alarm emails.
ALERT_EMAIL=ops@example.com
"""
VALUES = {
    "CLOUDFLARE_ZONE_ID": "zone123",
    "CLOUDFLARE_API_TOKEN": "token-abc",
    "HOSPITALSYSTEM_CONNECTION_STRING": CONNECTION,
    "ALERT_EMAIL": "ops@example.com",
}

FAKE_PLAYBOOK = r'''
import json, os, sys
with open(os.environ["FAKE_LOG"], "a") as log:
    log.write(json.dumps({
        "tool": "ansible-playbook", "argv": sys.argv[1:], "cwd": os.getcwd(),
        "key": os.environ.get("HOSPITALSYSTEM_JWT_SECRET"),
        "connection": os.environ.get("HOSPITALSYSTEM_CONNECTION_STRING"),
    }) + "\n")
sys.exit(int(os.environ["FAKE_PLAYBOOK_RC"]))
'''
FAKE_KUBECTL = r'''
import json, os, sys
args = sys.argv[1:]
with open(os.environ["FAKE_LOG"], "a") as log:
    log.write(json.dumps({"tool": "kubectl", "argv": args}) + "\n")
if "secret" in args:
    print(os.environ["FAKE_SECRET_HASH"], end="")
elif "deployment" in args:
    print(os.environ["FAKE_DEPLOYMENT"])
else:
    sys.exit(1)
'''


def deployment(started_with="hash-new", replicas=2, updated=2, ready=2):
    status = {"observedGeneration": 3, "replicas": replicas, "updatedReplicas": updated, "readyReplicas": ready}
    return {
        "metadata": {"name": "hospital-backend", "generation": 3,
                     "annotations": {"hospitalsystem.io/backend-secrets-hash": started_with}},
        "spec": {"replicas": replicas},
        # The API leaves out status counts that are 0.
        "status": {field: value for field, value in status.items() if value},
    }


class RotateTests(TestCase):
    def setUp(self):
        self.root = Path(self.enterContext(tempfile.TemporaryDirectory())).resolve()
        self.env_file = self.root / ".env.local"
        self.env_file.write_text(ENV_LOCAL)
        self.env_file.chmod(0o644)
        self.bin = self.root / "bin"
        self.bin.mkdir()
        (self.bin / "ansible-playbook").write_text(f"#!{sys.executable}\n{FAKE_PLAYBOOK}")
        (self.bin / "kubectl").write_text(f"#!{sys.executable}\n{FAKE_KUBECTL}")
        for tool in ("aws", "session-manager-plugin"):
            (self.bin / tool).write_text("#!/bin/sh\nexit 0\n")
        for tool in self.bin.iterdir():
            tool.chmod(0o755)
        self.log = self.root / "calls.log"

    def stack_up(self):
        vars_dir = self.root / "ansible/group_vars/all"
        vars_dir.mkdir(parents=True)
        (vars_dir / "terraform.yml").write_text(
            '# Generated by Terraform from terraform/locals.tf. Do not edit.\n'
            '"aws_region": "eu-north-1"\n"k8s_namespace": "hospitalsystem"\n'
        )
        (vars_dir / "main.yml").write_text((ROOT / "ansible/group_vars/all/main.yml").read_text())

    def run_script(self, *args, stdin="", playbook_rc=0, secret_hash="hash-new", live=None):
        env = {
            "PATH": f"{self.bin}:{os.environ['PATH']}",
            "HOME": str(self.root),
            "RETRY_DELAY": "0",
            "FAKE_LOG": str(self.log),
            "FAKE_PLAYBOOK_RC": str(playbook_rc),
            "FAKE_SECRET_HASH": secret_hash,
            "FAKE_DEPLOYMENT": json.dumps(live or deployment()),
        }
        result = subprocess.run(
            [sys.executable, str(SCRIPT), "--root", str(self.root), *args],
            env=env, input=stdin, capture_output=True, text=True, timeout=60,
        )
        key = self.saved_key()
        self.assertNotIn(key, result.stdout + result.stderr)
        for call in self.calls():
            self.assertNotIn(key, " ".join(call["argv"]))
        return result

    def saved_key(self):
        return re.search(r"^(?:export )?HOSPITALSYSTEM_JWT_SECRET=(.*)$",
                         self.env_file.read_text(), re.M).group(1)

    def calls(self):
        if not self.log.exists():
            return []
        return [json.loads(line) for line in self.log.read_text().splitlines()]

    def test_only_the_key_line_changes(self):
        result = self.run_script("--yes")
        self.assertEqual(result.returncode, 0, result.stderr)
        key = self.saved_key()
        self.assertRegex(key, r"^[A-Za-z0-9_-]{86}$")
        self.assertEqual(self.env_file.read_text(), ENV_LOCAL.replace(OLD_KEY, key))

    def test_file_ends_up_owner_only(self):
        self.run_script("--yes")
        self.assertEqual(stat.S_IMODE(self.env_file.stat().st_mode), 0o600)
        self.assertEqual(list(self.root.glob(".env.local.*")), [])

    def test_sourcing_the_file_still_gives_every_value(self):
        self.run_script("--yes")
        dump = f'{sys.executable} -c "import json, os, sys; json.dump(dict(os.environ), sys.stdout)"'
        result = subprocess.run(
            ["bash", "-c", f'set -euo pipefail; set -a; source "$1"; set +a; {dump}', "bash", str(self.env_file)],
            capture_output=True, text=True, check=True,
        )
        values = json.loads(result.stdout)
        self.assertEqual({name: values.get(name) for name in VALUES}, VALUES)
        self.assertEqual(values["HOSPITALSYSTEM_JWT_SECRET"], self.saved_key())

    def test_stack_down_runs_no_playbook(self):
        result = self.run_script("--yes")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("The next ./scripts/tf.sh apply stores the key.", result.stdout)
        self.assertEqual(self.calls(), [])

    def test_fills_in_the_first_key(self):
        example = (ROOT / ".env.example").read_text()
        self.env_file.write_text(example)
        result = self.run_script("--yes")
        self.assertEqual(result.returncode, 0, result.stderr)
        key = self.saved_key()
        self.assertRegex(key, r"^[A-Za-z0-9_-]{86}$")
        self.assertEqual(self.env_file.read_text(), example.replace(
            "\nHOSPITALSYSTEM_JWT_SECRET=\n", f"\nHOSPITALSYSTEM_JWT_SECRET={key}\n"))

    def test_declining_changes_nothing(self):
        result = self.run_script(stdin="n\n")
        self.assertEqual(result.returncode, 1)
        self.assertEqual(self.env_file.read_text(), ENV_LOCAL)
        self.assertEqual(stat.S_IMODE(self.env_file.stat().st_mode), 0o644)

    def test_stack_up_without_connection_string_changes_nothing(self):
        self.stack_up()
        self.env_file.write_text(ENV_LOCAL.replace(f"'{CONNECTION}'", ""))
        result = self.run_script("--yes")
        self.assertEqual(result.returncode, 1)
        self.assertIn("HOSPITALSYSTEM_CONNECTION_STRING isn't set", result.stderr)
        self.assertEqual(self.saved_key(), OLD_KEY)
        self.assertEqual(self.calls(), [])

    def test_stack_up_pushes_the_key_and_checks_the_backend(self):
        self.stack_up()
        result = self.run_script("--yes")
        self.assertEqual(result.returncode, 0, result.stderr)
        playbook, *kubectl_calls = self.calls()
        self.assertEqual(playbook["argv"], [PLAYBOOK])
        self.assertEqual(Path(playbook["cwd"]).resolve(), self.root)
        self.assertEqual(playbook["key"], self.saved_key())
        self.assertEqual(playbook["connection"], CONNECTION)
        self.assertEqual([call["tool"] for call in kubectl_calls], ["kubectl", "kubectl"])
        for call in kubectl_calls:
            self.assertEqual(call["argv"][:2], ["--kubeconfig", str(self.root / ".generated/kubeconfig")])
            self.assertIn("-n hospitalsystem", " ".join(call["argv"]))
        self.assertIn("hospital-backend restarted with the new key: 2 of 2 pods ready.", result.stdout)

    def test_playbook_failure_keeps_the_key_and_says_how_to_push_it(self):
        self.stack_up()
        result = self.run_script("--yes", playbook_rc=2)
        self.assertEqual(result.returncode, 1)
        self.assertNotEqual(self.saved_key(), OLD_KEY)
        self.assertIn(f"(set -a; source .env.local; ansible-playbook {PLAYBOOK})", result.stderr)
        self.assertEqual([call["tool"] for call in self.calls()], ["ansible-playbook"])

    def test_backend_on_an_older_secret_fails(self):
        self.stack_up()
        result = self.run_script("--yes", live=deployment(started_with="hash-old"))
        self.assertEqual(result.returncode, 1)
        self.assertIn("hospital-backend didn't record the new Secret's hash", result.stderr)

    def test_unready_pod_fails(self):
        self.stack_up()
        result = self.run_script("--yes", live=deployment(ready=1))
        self.assertEqual(result.returncode, 1)
        self.assertIn("hospital-backend has 2 of 2 pods on the new Secret and 1 ready", result.stderr)

    def test_backend_scaled_to_zero_passes(self):
        self.stack_up()
        result = self.run_script("--yes", live=deployment(replicas=0, updated=0, ready=0))
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("hospital-backend is scaled to 0; its next scale-up reads the new key.", result.stdout)


class SaveKeyTests(TestCase):
    def save(self, text):
        path = Path(self.enterContext(tempfile.TemporaryDirectory())) / ".env.local"
        path.write_bytes(text.encode())
        rotate.save_key(path, "NEW")
        return path.read_bytes().decode()

    def test_adds_the_line_when_there_is_none(self):
        self.assertEqual(self.save("A=1"), "A=1\nHOSPITALSYSTEM_JWT_SECRET=NEW\n")

    def test_changes_only_the_assignment_and_keeps_line_endings(self):
        text = ("# HOSPITALSYSTEM_JWT_SECRET=commented\r\n"
                "HOSPITALSYSTEM_JWT_SECRET_OLD=other\r\n"
                "  export HOSPITALSYSTEM_JWT_SECRET='old'\r\n"
                "B=2")
        self.assertEqual(self.save(text), text.replace("'old'", "NEW"))


if __name__ == "__main__":
    main()
