resource "local_file" "ansible_vars" {
  filename        = "${path.module}/../ansible/group_vars/all/terraform.yml"
  file_permission = "0644"
  content         = "# Generated by Terraform from terraform/locals.tf. Do not edit.\n${yamlencode(local.ansible_vars)}"
}

resource "terraform_data" "ansible_bootstrap" {
  count = var.run_ansible_bootstrap ? 1 : 0

  triggers_replace = {
    bootstrap_vars_hash = sha256(jsonencode(local.ansible_vars))
    files_hash          = local.ansible_bootstrap_files_hash
    cluster_name        = aws_eks_cluster.main.name
    region              = var.aws_region
  }

  provisioner "local-exec" {
    working_dir = "${path.module}/.."
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail

      if [ -f .env.local ]; then
        set -a
        source .env.local
        set +a
      fi

      ansible-playbook ansible/playbooks/bootstrap.yml
    EOT
  }

  depends_on = [
    aws_eks_cluster.main,
    aws_eks_node_group.hospitalsystempr1,
    aws_iam_role.eks_deploy_hospitalsystem,
    aws_acm_certificate_validation.app,
    terraform_data.initial_ecr_image_push,
    local_file.ansible_vars,
    # The bootstrap installs the controller, which needs its permissions to create the ALB.
    aws_iam_role_policy.load_balancer_controller,
    # The playbooks reach the private API through an SSM session on this instance.
    aws_instance.ops,
    aws_iam_role_policy_attachment.ops_ssm,
    aws_vpc_endpoint.ssm,
    aws_vpc_security_group_egress_rule.ops_vpc_https,
    aws_vpc_security_group_ingress_rule.eks_api_from_ops,
    aws_vpc_security_group_ingress_rule.vpc_endpoints_https
  ]
}

resource "terraform_data" "kubernetes_cleanup" {
  count = var.run_ansible_bootstrap ? 1 : 0

  # Passed explicitly so cleanup still works if the generated vars file is gone.
  input = {
    eks_cluster_name = aws_eks_cluster.main.name
    aws_region       = var.aws_region
    vpc_id           = aws_vpc.kubes.id
    k8s_namespace    = local.k8s_namespace
    ops_instance_id  = aws_instance.ops.id
  }

  provisioner "local-exec" {
    when        = destroy
    working_dir = "${path.module}/.."
    interpreter = ["/bin/bash", "-c"]
    command     = "ansible-playbook ansible/playbooks/cleanup-kubernetes.yml -e '${jsonencode(self.input)}' || true"
  }

  # Destroyed after the cleanup runs, so it can still reach the private API and
  # the controller can still delete the ALB.
  depends_on = [
    aws_eks_cluster.main,
    aws_eks_node_group.hospitalsystempr1,
    aws_iam_role_policy.load_balancer_controller,
    aws_instance.ops,
    aws_iam_role_policy_attachment.ops_ssm,
    aws_vpc_endpoint.ssm,
    aws_vpc_security_group_egress_rule.ops_vpc_https,
    aws_vpc_security_group_ingress_rule.eks_api_from_ops,
    aws_vpc_security_group_ingress_rule.vpc_endpoints_https
  ]
}
