apiVersion: v1
kind: Service
metadata:
  name: hospital-backend
  namespace: hospitalsystem
  labels:
    app.kubernetes.io/name: hospital-backend
    app.kubernetes.io/part-of: hospitalsystem
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hospital-backend
  ports:
    - name: http
      port: 80
      targetPort: http
