---
- name: Configure local kubeconfig for EKS
  hosts: local
  gather_facts: false

  tasks:
    - name: Update kubeconfig
      ansible.builtin.import_tasks: ../tasks/kubeconfig.yml

    - name: Show kubeconfig result
      ansible.builtin.debug:
        var: kubeconfig_update.stdout

